version: "3.7"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "toor"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    volumes:
      - postgres_host
volumes:
  pgdata: {}
networks:
  postgres_network:
    name: postgres_net
    driver: bridge
